workspace:
  base: /var/www/owncloud
  path: apps/encryption

branches: [master, release*, release/*]

pipeline:
  install-server:
    image: patrickjahns/occore
    pull: true
    exclude: "apps/encryption"
    version: ${OC_VERSION}
    db_type: ${DB_TYPE}
    db_host: ${DB_HOST}

  code-check:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ../../lib/composer/bin/parallel-lint . --exclude 3rdparty --exclude build .
      #- cd /var/www/owncloud
      #- php ./occ app:check-code encryption -c private -c strong-comparison
      #- php ./occ app:check-code encryption -c deprecation
    when:
      matrix:
        TEST_SUITE: phpunit


  phpunit:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - phpdbg -d memory_limit=4096M -rr  ../../lib/composer/bin/phpunit --configuration tests/phpunit.xml
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
     - tests/output
    files:
     - '*.xml'
    when:
      local: false
      matrix:
        TEST_SUITE: phpunit
        PHP_VERSION: 7.1

  scrutinizer:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - wget -q https://scrutinizer-ci.com/ocular.phar
      - php ocular.phar code-coverage:upload --format=php-clover tests/output/clover.xml --access-token="09d3585a3ed80b16c3b9eed9912b27cfd85e6ed8c190d95893a02bef73dbde68"
    when:
      local: false
      matrix:
        TEST_SUITE: phpunit
        PHP_VERSION: 7.1

  print-log:
    image: owncloudci/php
    commands:
     - cat /var/www/owncloud/data/owncloud.log
    when:
      status: [ failure ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      local: false
      status: [ changed, failure ]
      event: [ push, tag ]


matrix:
  include:
    # UnitTests

    #master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    # stable10
    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite